name: CD

on: [push]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i

  deploy:
    needs: build-and-test

    runs-on: ubuntu-latest

    steps:
      - name: Executing remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          
          script: |
            cd ~/backend/Express-MongoDB
            echo "------ cd to app --------"
            ls
            git pull origin main
            echo "------ Pull Complete -------"
            git status
            echo "------ npm commands -------"
            npm i
            pm2 start app.js
 
